# Generated by Django 3.2.9 on 2023-02-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_urun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='hakkimizda_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Hakımızda Yazısı arapca'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='hakkimizda_de',
            field=models.TextField(blank=True, null=True, verbose_name='Hakımızda Yazısı Almanca'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='hakkimizda_en',
            field=models.TextField(blank=True, null=True, verbose_name='Hakımızda Yazısı İngilizce'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='hakkimizda_tr',
            field=models.TextField(verbose_name='Hakkımızda Yazısı Türkçe'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim_ar',
            field=models.CharField(max_length=200, verbose_name='İsim arapca'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim_de',
            field=models.CharField(max_length=200, verbose_name='İsim almanca'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim_en',
            field=models.CharField(max_length=200, verbose_name='İsim inglizce'),
        ),
    ]
