# Generated by Django 4.0.5 on 2023-03-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20230228_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='hakkimizda_ar',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='hakkimizda_de',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='hakkimizda_en',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='hakkimizda_tr',
        ),
    ]
