# Generated by Django 4.0.5 on 2023-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_urun_hakkimizda_ar_remove_urun_hakkimizda_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gsefoto/', verbose_name='Size Ait Olan Resmi Ekleyin'),
        ),
    ]
