# Generated by Django 3.2.9 on 2023-03-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_urun_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=200)),
                ('ac_type', models.CharField(max_length=200)),
                ('qty', models.BigIntegerField()),
            ],
        ),
    ]
