# Generated by Django 3.2.9 on 2023-03-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_all_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='namesurname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='web_site',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
