# Generated by Django 4.0.5 on 2023-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
