# Generated by Django 4.0.5 on 2023-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_rfq_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq',
            name='price',
        ),
        migrations.AddField(
            model_name='all_product',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
