# Generated by Django 3.2.18 on 2023-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_remove_rfq_price_all_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='dil_kayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_bilgisi', models.GenericIPAddressField(verbose_name='Şahıs İp Adresi')),
            ],
        ),
    ]
