# Generated by Django 3.2.18 on 2023-04-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_dil_kayit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dil_kayit',
        ),
    ]
